[package]
name = "rabe-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde = "1.0"
serde_json = "1.0"
rabe = { path = "./rabe" }
serde-wasm-bindgen = "0.1"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }